### ISSUE TITLE
Admonition compatibility ?

### ISSUE THREAD

**Issue by Ninluc** [jmerle/inkdrop-table-editor#15]
Hi, thanks for this useful plugin !

I have some troubles when creating a new line in an [admonition](https://github.com/libeanim/inkdrop-admonition). The thing is that the body of an admonition starts with a "|" and I guess this extension is interpreting the line as a table. 

I've found a fix when creating a new line : I simply do <kbd>shift</kbd> + <kbd>enter</kbd>.

But there are another problems when for example I want to do a <kbd>ctrl</kbd> + <kbd>←</kbd>, this extension parse the whole thing as a table.

I imagine a fix would be to detect the head of the admonition who looks like this :
```md
[[admonition-type | Title ]]
```

Thanks in advance...

**Comment by jmerle** [comment]
Fixed in 19a55cb73c20605c30d2d2507919eca30a23e316, will be released within a few hours. Thanks for reporting the issue!

**Comment by Ninluc** [comment]
Hey, sorry for bothering once again...

The fix works, but only when non-indented. Sometimes I need the admonition to be inside a list for example
![image](https://user-images.githubusercontent.com/56800521/201531218-291fa437-6f5a-419e-b735-361ed1398381.png)

[This `startsWith`](https://github.com/jmerle/inkdrop-table-editor/commit/19a55cb73c20605c30d2d2507919eca30a23e316#diff-d64728d3e28534afadaa4f2a7d89b8150cc8afce4a548080bf129470abfb6a2aR68) and the one a couple line after may be the problem.

Thanks in advance...

**Comment by jmerle** [comment]
No worries, this is clearly a bug. Fixed in 0b4067ed8ea67e10a40402e4746625f099d3e2d1, released in v1.1.2.

**Comment by Ninluc** [comment]
Thanks a lot !
