### ISSUE TITLE
disable table edit in fenced code blocks

### ISSUE THREAD

**Issue by lorenzdiener** [jmerle/inkdrop-table-editor#17]
Hi,

thanks for this plugin! I enjoy using it. However today I came across an - at least for me - unexpected behavior. I use [fenced code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) in markdown to write down certain things where lines starting with `|` should not be automatically detected as markdown table. E.g. I'm writing [Gherkin syntax](https://cucumber.io/docs/gherkin/reference/#:~:text=*.feature%20file.-,Scenario%20Outline,-The%20Scenario%20Outline) like this:

![image](https://user-images.githubusercontent.com/25670707/212753575-11e1f28e-144d-4091-bbe6-ff60ab2726d5.png)

In Gherkin the table schema for the `Examples` section differs from markdown syntax. The line `| --- |` must be omitted. However, every time I add a line to the table inside the code block, the second line is added again.

I'm not sure what would be the best behavior. My first approach would be to disable auto table editing entirely in fenced code blocks as I also initially expected when I read the comment above [acceptTableEdit function](https://github.com/jmerle/inkdrop-table-editor/blob/a8a6c57bec04b1be62a6c44f2affc346648f92dd/src/CodeMirrorTextEditor.js#L69).

If you accept this issue as useful / possible improvement, I'd be happy to offer creating a PR. Just let me know :)

A question regarding the implementation would be, how to detect a code block correctly to  make sure table editing below a fenced code block keeps working. Maybe interpreting back ticks with provided highlight language as start and back ticks without one as end is an acceptable way (though fenced code blocks without highlight language wouldn't be detected).

Thanks in advance!

**Comment by jmerle** [comment]
I implemented your first approach (disabling table editing in all code blocks) in ce3a1179cbea75e7996fd0c2f32beac1a213ba41 and released the changes in v1.2.0. Thanks for reporting the issue!

**Comment by lorenzdiener** [comment]
Works like expected, thanks a lot!
