### ISSUE TITLE
Error installing plugin in beta v5.0.0-beta1

### ISSUE THREAD

**Issue by raelb** [jmerle/inkdrop-table-editor#3]
Hi,
I received an error trying to install this plugin in v5.0.0-beta1

![image](https://user-images.githubusercontent.com/13108198/89526629-5401a580-d7e8-11ea-8d76-b3c24381f3d5.png)

I'm on Windows 10 x64

**Comment by raelb** [comment]
Here is the full log:

[2020-08-06T11_22_46_024Z-debug.log](https://github.com/jmerle/inkdrop-table-editor/files/5034513/2020-08-06T11_22_46_024Z-debug.log)

**Comment by jmerle** [comment]
This is an issue with npm, which currently has an outage which makes it impossible to install scoped packages (like `@susisu/mte-kernel`). The status of that incident can be seen at [status.npmjs.org](https://status.npmjs.org/). When the npmjs incident has been resolved you should be able to install it.

**Comment by raelb** [comment]
ok

**Comment by jmerle** [comment]
It should be working now.
